import { MigrationInterface, QueryRunner } from 'typeorm';

/**
 * Initial schema: 17 domain tables + 2 lookups.
 * Hand-authored so the advanced Postgres bits (enum types, ref-code sequences +
 * triggers, partial unique indexes, GIN/tsvector, CHECK constraints) are explicit.
 */
export class InitialSchema1710000000000 implements MigrationInterface {
  name = 'InitialSchema1710000000000';

  public async up(q: QueryRunner): Promise<void> {
    // ── Extensions ────────────────────────────────────────────────────────────
    await q.query(`CREATE EXTENSION IF NOT EXISTS citext`);
    await q.query(`CREATE EXTENSION IF NOT EXISTS pg_trgm`);

    // ── Enum types ────────────────────────────────────────────────────────────
    const enums: Array<[string, string[]]> = [
      ['user_role', ['ADMIN', 'AGENT']],
      ['user_status', ['ACTIVE', 'INACTIVE', 'SUSPENDED']],
      ['contact_type', ['OWNER', 'BUYER', 'TENANT', 'LANDLORD', 'INVESTOR']],
      ['contact_source', ['WEBSITE', 'REFERRAL', 'WALK_IN', 'PHONE', 'SOCIAL', 'OTHER']],
      ['property_status', ['DRAFT', 'ACTIVE', 'RESERVED', 'SOLD', 'RENTED', 'ARCHIVED']],
      ['listing_type', ['SALE', 'RENT']],
      ['property_type', ['APARTMENT', 'HOUSE', 'VILLA', 'LAND', 'OFFICE', 'SHOP', 'WAREHOUSE', 'BUILDING']],
      ['orientation', ['NORTH', 'SOUTH', 'EAST', 'WEST']],
      ['building_condition', ['NEW_CONSTRUCTION', 'OLD_CONSTRUCTION']],
      ['agreement_type', ['OPEN', 'EXCLUSIVE']],
      ['agreement_status', ['DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED']],
      ['opportunity_status', ['NEW', 'QUALIFIED', 'MATCHING', 'VIEWING', 'NEGOTIATING', 'WON', 'LOST']],
      ['match_status', ['SUGGESTED', 'SHARED', 'VIEWING', 'REJECTED', 'ACCEPTED']],
      ['viewing_status', ['SCHEDULED', 'COMPLETED', 'CANCELLED', 'NO_SHOW']],
      ['offer_status', ['SUBMITTED', 'COUNTERED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN']],
      ['deal_type', ['SALE', 'RENT']],
      ['deal_status', ['OPEN', 'PENDING', 'CLOSED_WON', 'CLOSED_LOST', 'CANCELLED']],
      ['contract_type', ['SALE', 'RENTAL']],
      ['contract_status', ['DRAFT', 'ACTIVE', 'EXPIRED', 'TERMINATED', 'RENEWED', 'COMPLETED']],
      ['reminder_type', ['EXPIRY', 'RENT_DUE', 'FOLLOW_UP', 'CUSTOM']],
      ['reminder_status', ['PENDING', 'SENT', 'DISMISSED', 'DONE']],
      ['commission_status', ['PENDING', 'INVOICED', 'PARTIAL', 'PAID', 'CANCELLED']],
      ['receiver_type', ['COMPANY', 'AGENT', 'PARTNER_COMPANY']],
      ['activity_type', ['CALL', 'MEETING', 'MESSAGE', 'NOTE', 'FOLLOW_UP']],
      ['task_priority', ['LOW', 'MEDIUM', 'HIGH']],
      ['task_status', ['OPEN', 'IN_PROGRESS', 'DONE', 'CANCELLED']],
      ['document_category', ['OWNERSHIP', 'CONTRACT', 'IDENTITY', 'FINANCIAL', 'OTHER']],
      ['document_status', ['PENDING', 'VERIFIED', 'REJECTED', 'EXPIRED']],
    ];
    for (const [name, values] of enums) {
      await q.query(`CREATE TYPE ${name} AS ENUM (${values.map((v) => `'${v}'`).join(', ')})`);
    }

    // ── Shared functions ──────────────────────────────────────────────────────
    await q.query(`
      CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
      BEGIN NEW.updated_at = now(); RETURN NEW; END;
      $$ LANGUAGE plpgsql;
    `);
    await q.query(`
      CREATE OR REPLACE FUNCTION assign_ref_code() RETURNS trigger AS $$
      DECLARE v_prefix text := TG_ARGV[0]; v_seq text := TG_ARGV[1];
      BEGIN
        IF TG_TABLE_NAME = 'properties' THEN
          IF NEW.property_code IS NULL THEN
            NEW.property_code := v_prefix || lpad(nextval(v_seq)::text, 4, '0');
          END IF;
        ELSE
          IF NEW.code IS NULL THEN
            NEW.code := v_prefix || lpad(nextval(v_seq)::text, 4, '0');
          END IF;
        END IF;
        RETURN NEW;
      END;
      $$ LANGUAGE plpgsql;
    `);

    // ── Ref-code sequences ────────────────────────────────────────────────────
    for (const s of [
      'seq_contacts',
      'seq_properties',
      'seq_listing_agreements',
      'seq_opportunities',
      'seq_deals',
      'seq_contracts',
    ]) {
      await q.query(`CREATE SEQUENCE ${s} START 1`);
    }

    const ts = `created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()`;

    // ── Lookups ───────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE heating_types (
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        key text NOT NULL UNIQUE,
        label_json jsonb NOT NULL,
        is_active boolean NOT NULL DEFAULT true,
        sort_order smallint NOT NULL DEFAULT 0
      )`);
    await q.query(`
      CREATE TABLE document_types (
        id smallint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        category document_category NOT NULL,
        key text NOT NULL UNIQUE,
        label_json jsonb NOT NULL,
        is_active boolean NOT NULL DEFAULT true
      )`);

    // ── users ─────────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE users (
        id uuid PRIMARY KEY,
        full_name text NOT NULL,
        email citext NOT NULL,
        phone text,
        password_hash text NOT NULL,
        role user_role NOT NULL DEFAULT 'AGENT',
        status user_status NOT NULL DEFAULT 'ACTIVE',
        photo_url text,
        title_json jsonb,
        bio_json jsonb,
        ${ts}
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_users_email ON users (email)`);

    // ── contacts ──────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE contacts (
        id uuid PRIMARY KEY,
        code text NOT NULL,
        full_name text NOT NULL,
        phone text,
        email citext,
        contact_type contact_type NOT NULL,
        source contact_source NOT NULL DEFAULT 'OTHER',
        notes text,
        created_by uuid REFERENCES users(id) ON DELETE SET NULL,
        ${ts}
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_contacts_code ON contacts (code)`);

    // ── properties ────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE properties (
        id uuid PRIMARY KEY,
        property_code text NOT NULL,
        status property_status NOT NULL DEFAULT 'DRAFT',
        listing_type listing_type NOT NULL,
        property_type property_type NOT NULL,
        title_json jsonb NOT NULL,
        description_json jsonb,
        price numeric(14,2) NOT NULL CHECK (price >= 0),
        currency char(3) NOT NULL DEFAULT 'EUR' CHECK (currency ~ '^[A-Z]{3}$'),
        country text NOT NULL,
        city text NOT NULL,
        area text,
        cadastral_zone text,
        address text,
        latitude numeric(9,6) CHECK (latitude BETWEEN -90 AND 90),
        longitude numeric(9,6) CHECK (longitude BETWEEN -180 AND 180),
        bedrooms smallint CHECK (bedrooms >= 0),
        bathrooms smallint CHECK (bathrooms >= 0),
        toilets smallint CHECK (toilets >= 0),
        floor smallint,
        size_m2 numeric(10,2) CHECK (size_m2 >= 0),
        lot_size_m2 numeric(10,2) CHECK (lot_size_m2 >= 0),
        terrace_m2 numeric(10,2) CHECK (terrace_m2 >= 0),
        basement_m2 numeric(10,2) CHECK (basement_m2 >= 0),
        garage smallint CHECK (garage >= 0),
        parking boolean NOT NULL DEFAULT false,
        elevator boolean NOT NULL DEFAULT false,
        balconies smallint CHECK (balconies >= 0),
        storage boolean NOT NULL DEFAULT false,
        furnished boolean NOT NULL DEFAULT false,
        heating_type_id smallint REFERENCES heating_types(id) ON DELETE RESTRICT,
        orientation orientation,
        building_condition building_condition,
        year_built smallint CHECK (year_built BETWEEN 1800 AND (extract(year from now())::int + 5)),
        is_featured boolean NOT NULL DEFAULT false,
        attributes_json jsonb NOT NULL DEFAULT '{}'::jsonb,
        agent_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        owner_contact_id uuid REFERENCES contacts(id) ON DELETE RESTRICT,
        published_date date,
        created_by uuid REFERENCES users(id) ON DELETE SET NULL,
        search_tsv tsvector GENERATED ALWAYS AS (
          to_tsvector('simple',
            coalesce(title_json->>'en','') || ' ' || coalesce(title_json->>'sq','') || ' ' || coalesce(title_json->>'de','') || ' ' ||
            coalesce(description_json->>'en','') || ' ' || coalesce(description_json->>'sq','') || ' ' || coalesce(description_json->>'de','')
          )
        ) STORED,
        ${ts},
        CONSTRAINT ck_properties_title_i18n CHECK (title_json ? 'en' AND title_json ? 'sq' AND title_json ? 'de')
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_properties_code ON properties (property_code)`);
    await q.query(`CREATE INDEX ix_properties_status ON properties (status)`);
    await q.query(`CREATE INDEX ix_properties_listing_type ON properties (listing_type)`);
    await q.query(`CREATE INDEX ix_properties_property_type ON properties (property_type)`);
    await q.query(`CREATE INDEX ix_properties_price ON properties (price)`);
    await q.query(`CREATE INDEX ix_properties_city_area ON properties (city, area)`);
    await q.query(`CREATE INDEX ix_properties_featured ON properties (is_featured) WHERE is_featured`);
    await q.query(`CREATE INDEX ix_properties_attrs_gin ON properties USING gin (attributes_json)`);
    await q.query(`CREATE INDEX ix_properties_tsv ON properties USING gin (search_tsv)`);
    await q.query(`CREATE INDEX ix_properties_city_trgm ON properties USING gin (city gin_trgm_ops)`);
    await q.query(`CREATE INDEX ix_properties_area_trgm ON properties USING gin (area gin_trgm_ops)`);

    // ── property_images ───────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE property_images (
        id uuid PRIMARY KEY,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        image_url text NOT NULL,
        storage_key text,
        is_cover boolean NOT NULL DEFAULT false,
        sort_order integer NOT NULL DEFAULT 0,
        ${ts}
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_property_images_cover ON property_images (property_id) WHERE is_cover`);
    await q.query(`CREATE INDEX ix_property_images_property_sort ON property_images (property_id, sort_order)`);

    // ── property_documents ────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE property_documents (
        id uuid PRIMARY KEY,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        document_type_id smallint NOT NULL REFERENCES document_types(id) ON DELETE RESTRICT,
        file_url text NOT NULL,
        storage_key text,
        status document_status NOT NULL DEFAULT 'PENDING',
        notes text,
        uploaded_by uuid REFERENCES users(id) ON DELETE SET NULL,
        ${ts}
      )`);
    await q.query(`CREATE INDEX ix_property_documents_property ON property_documents (property_id)`);

    // ── listing_agreements ────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE listing_agreements (
        id uuid PRIMARY KEY,
        code text NOT NULL,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        owner_contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
        agent_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        agreement_type agreement_type NOT NULL,
        start_date date NOT NULL,
        end_date date,
        commission_percentage numeric(5,2) CHECK (commission_percentage >= 0 AND commission_percentage <= 100),
        status agreement_status NOT NULL DEFAULT 'DRAFT',
        ${ts},
        CONSTRAINT ck_la_dates CHECK (end_date IS NULL OR end_date >= start_date)
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_listing_agreements_code ON listing_agreements (code)`);
    await q.query(`CREATE UNIQUE INDEX uq_active_exclusive ON listing_agreements (property_id) WHERE status = 'ACTIVE' AND agreement_type = 'EXCLUSIVE'`);

    // ── opportunities ─────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE opportunities (
        id uuid PRIMARY KEY,
        code text NOT NULL,
        contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
        assigned_agent_id uuid REFERENCES users(id) ON DELETE SET NULL,
        property_type property_type NOT NULL,
        listing_type listing_type NOT NULL,
        country text,
        city text,
        area text,
        budget_min numeric(14,2) CHECK (budget_min >= 0),
        budget_max numeric(14,2) CHECK (budget_max >= 0),
        currency char(3) NOT NULL DEFAULT 'EUR',
        status opportunity_status NOT NULL DEFAULT 'NEW',
        requirements_json jsonb NOT NULL DEFAULT '{}'::jsonb,
        created_by uuid REFERENCES users(id) ON DELETE SET NULL,
        ${ts},
        CONSTRAINT ck_opp_budget CHECK (budget_max IS NULL OR budget_min IS NULL OR budget_max >= budget_min)
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_opportunities_code ON opportunities (code)`);
    await q.query(`CREATE INDEX ix_opportunities_status ON opportunities (status)`);
    await q.query(`CREATE INDEX ix_opportunities_reqs_gin ON opportunities USING gin (requirements_json)`);

    // ── matches ───────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE matches (
        id uuid PRIMARY KEY,
        opportunity_id uuid NOT NULL REFERENCES opportunities(id) ON DELETE CASCADE,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
        status match_status NOT NULL DEFAULT 'SUGGESTED',
        match_score numeric(5,2),
        ${ts},
        CONSTRAINT uq_match UNIQUE (opportunity_id, property_id)
      )`);

    // ── viewings ──────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE viewings (
        id uuid PRIMARY KEY,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        opportunity_id uuid REFERENCES opportunities(id) ON DELETE SET NULL,
        contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
        agent_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
        scheduled_at timestamptz NOT NULL,
        status viewing_status NOT NULL DEFAULT 'SCHEDULED',
        feedback text,
        ${ts}
      )`);
    await q.query(`CREATE INDEX ix_viewings_scheduled ON viewings (scheduled_at)`);

    // ── offers ────────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE offers (
        id uuid PRIMARY KEY,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        opportunity_id uuid REFERENCES opportunities(id) ON DELETE SET NULL,
        buyer_contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
        offered_amount numeric(14,2) NOT NULL CHECK (offered_amount >= 0),
        currency char(3) NOT NULL DEFAULT 'EUR',
        status offer_status NOT NULL DEFAULT 'SUBMITTED',
        notes text,
        created_by uuid REFERENCES users(id) ON DELETE SET NULL,
        ${ts}
      )`);
    await q.query(`CREATE INDEX ix_offers_property ON offers (property_id)`);

    // ── deals ─────────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE deals (
        id uuid PRIMARY KEY,
        code text NOT NULL,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        opportunity_id uuid REFERENCES opportunities(id) ON DELETE SET NULL,
        buyer_contact_id uuid REFERENCES contacts(id) ON DELETE RESTRICT,
        seller_contact_id uuid REFERENCES contacts(id) ON DELETE RESTRICT,
        agent_user_id uuid NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
        deal_type deal_type NOT NULL,
        final_price numeric(14,2) CHECK (final_price >= 0),
        madem_commission_value numeric(14,2) CHECK (madem_commission_value >= 0),
        commission_paid boolean NOT NULL DEFAULT false,
        currency char(3) NOT NULL DEFAULT 'EUR',
        status deal_status NOT NULL DEFAULT 'OPEN',
        closed_at timestamptz,
        ${ts}
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_deals_code ON deals (code)`);
    await q.query(`CREATE INDEX ix_deals_status ON deals (status)`);
    await q.query(`CREATE INDEX ix_deals_closed_revenue ON deals (closed_at) WHERE status = 'CLOSED_WON'`);
    await q.query(`
      CREATE INDEX ix_deals_unpaid_commissions
      ON deals (created_at DESC)
      WHERE status = 'CLOSED_WON'
        AND commission_paid = false
        AND madem_commission_value IS NOT NULL
        AND madem_commission_value > 0
    `);

    // ── contracts ─────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE contracts (
        id uuid PRIMARY KEY,
        code text NOT NULL,
        deal_id uuid REFERENCES deals(id) ON DELETE RESTRICT,
        property_id uuid NOT NULL REFERENCES properties(id) ON DELETE RESTRICT,
        owner_contact_id uuid NOT NULL REFERENCES contacts(id) ON DELETE RESTRICT,
        counterparty_contact_id uuid REFERENCES contacts(id) ON DELETE RESTRICT,
        agent_user_id uuid REFERENCES users(id) ON DELETE RESTRICT,
        start_date date NOT NULL,
        end_date date,
        contract_type contract_type NOT NULL,
        status contract_status NOT NULL DEFAULT 'DRAFT',
        ${ts},
        CONSTRAINT ck_contract_dates CHECK (end_date IS NULL OR end_date >= start_date),
        CONSTRAINT ck_contract_rental_end CHECK (contract_type <> 'RENTAL' OR end_date IS NOT NULL)
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_contracts_code ON contracts (code)`);
    await q.query(`CREATE UNIQUE INDEX uq_active_rental ON contracts (property_id) WHERE status = 'ACTIVE' AND contract_type = 'RENTAL'`);
    await q.query(`CREATE INDEX ix_contracts_end_date ON contracts (end_date)`);
    await q.query(`CREATE INDEX ix_contracts_status ON contracts (status)`);

    // ── contract_reminders ────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE contract_reminders (
        id uuid PRIMARY KEY,
        contract_id uuid NOT NULL REFERENCES contracts(id) ON DELETE CASCADE,
        type reminder_type NOT NULL DEFAULT 'EXPIRY',
        remind_at timestamptz NOT NULL,
        message text,
        status reminder_status NOT NULL DEFAULT 'PENDING',
        sent_at timestamptz,
        ${ts}
      )`);
    await q.query(`CREATE INDEX ix_contract_reminders_due ON contract_reminders (remind_at) WHERE status = 'PENDING'`);

    // ── commissions ───────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE commissions (
        id uuid PRIMARY KEY,
        deal_id uuid NOT NULL REFERENCES deals(id) ON DELETE RESTRICT,
        total_amount numeric(14,2) NOT NULL CHECK (total_amount >= 0),
        currency char(3) NOT NULL DEFAULT 'EUR',
        status commission_status NOT NULL DEFAULT 'PENDING',
        ${ts}
      )`);
    await q.query(`CREATE UNIQUE INDEX uq_commissions_deal ON commissions (deal_id)`);

    // ── commission_splits ─────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE commission_splits (
        id uuid PRIMARY KEY,
        commission_id uuid NOT NULL REFERENCES commissions(id) ON DELETE CASCADE,
        receiver_type receiver_type NOT NULL,
        receiver_user_id uuid REFERENCES users(id) ON DELETE SET NULL,
        receiver_label text,
        percentage numeric(5,2) CHECK (percentage >= 0 AND percentage <= 100),
        amount numeric(14,2) CHECK (amount >= 0),
        ${ts},
        CONSTRAINT ck_split_receiver CHECK (receiver_type <> 'AGENT' OR receiver_user_id IS NOT NULL)
      )`);
    await q.query(`CREATE INDEX ix_commission_splits_commission ON commission_splits (commission_id)`);

    // ── activities ────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE activities (
        id uuid PRIMARY KEY,
        type activity_type NOT NULL,
        contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
        property_id uuid REFERENCES properties(id) ON DELETE SET NULL,
        opportunity_id uuid REFERENCES opportunities(id) ON DELETE SET NULL,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        note text,
        created_by uuid REFERENCES users(id) ON DELETE SET NULL,
        ${ts},
        CONSTRAINT ck_activity_entity CHECK (
          contact_id IS NOT NULL OR property_id IS NOT NULL OR opportunity_id IS NOT NULL OR deal_id IS NOT NULL
        )
      )`);
    await q.query(`CREATE INDEX ix_activities_contact ON activities (contact_id)`);
    await q.query(`CREATE INDEX ix_activities_property ON activities (property_id)`);
    await q.query(`CREATE INDEX ix_activities_opportunity ON activities (opportunity_id)`);
    await q.query(`CREATE INDEX ix_activities_deal ON activities (deal_id)`);

    // ── tasks ─────────────────────────────────────────────────────────────────
    await q.query(`
      CREATE TABLE tasks (
        id uuid PRIMARY KEY,
        title text NOT NULL,
        description text,
        assigned_to uuid REFERENCES users(id) ON DELETE SET NULL,
        contact_id uuid REFERENCES contacts(id) ON DELETE SET NULL,
        property_id uuid REFERENCES properties(id) ON DELETE SET NULL,
        opportunity_id uuid REFERENCES opportunities(id) ON DELETE SET NULL,
        deal_id uuid REFERENCES deals(id) ON DELETE SET NULL,
        due_date timestamptz,
        priority task_priority NOT NULL DEFAULT 'MEDIUM',
        status task_status NOT NULL DEFAULT 'OPEN',
        created_by uuid REFERENCES users(id) ON DELETE SET NULL,
        ${ts}
      )`);
    await q.query(`CREATE INDEX ix_tasks_assignee ON tasks (assigned_to, status, due_date)`);

    // ── updated_at triggers ───────────────────────────────────────────────────
    const tablesWithUpdated = [
      'users', 'contacts', 'properties', 'property_images', 'property_documents',
      'listing_agreements', 'opportunities', 'matches', 'viewings', 'offers',
      'deals', 'contracts', 'contract_reminders', 'commissions', 'commission_splits',
      'activities', 'tasks',
    ];
    for (const t of tablesWithUpdated) {
      await q.query(`CREATE TRIGGER trg_${t}_updated BEFORE UPDATE ON ${t} FOR EACH ROW EXECUTE FUNCTION set_updated_at()`);
    }

    // ── ref-code triggers ─────────────────────────────────────────────────────
    const coded: Array<[string, string, string]> = [
      ['contacts', 'CN-', 'seq_contacts'],
      ['properties', 'M-', 'seq_properties'],
      ['listing_agreements', 'LA-', 'seq_listing_agreements'],
      ['opportunities', 'OP-', 'seq_opportunities'],
      ['deals', 'DL-', 'seq_deals'],
      ['contracts', 'CT-', 'seq_contracts'],
    ];
    for (const [table, prefix, seq] of coded) {
      await q.query(
        `CREATE TRIGGER trg_${table}_code BEFORE INSERT ON ${table} FOR EACH ROW EXECUTE FUNCTION assign_ref_code('${prefix}', '${seq}')`,
      );
    }
  }

  public async down(q: QueryRunner): Promise<void> {
    const tables = [
      'tasks', 'activities', 'commission_splits', 'commissions', 'contract_reminders',
      'contracts', 'deals', 'offers', 'viewings', 'matches', 'opportunities',
      'listing_agreements', 'property_documents', 'property_images', 'properties',
      'contacts', 'users', 'document_types', 'heating_types',
    ];
    for (const t of tables) await q.query(`DROP TABLE IF EXISTS ${t} CASCADE`);

    for (const s of [
      'seq_contacts', 'seq_properties', 'seq_listing_agreements',
      'seq_opportunities', 'seq_deals', 'seq_contracts',
    ]) {
      await q.query(`DROP SEQUENCE IF EXISTS ${s}`);
    }

    await q.query(`DROP FUNCTION IF EXISTS assign_ref_code()`);
    await q.query(`DROP FUNCTION IF EXISTS set_updated_at()`);

    const enumTypes = [
      'document_status', 'document_category', 'task_status', 'task_priority', 'activity_type',
      'receiver_type', 'commission_status', 'reminder_status', 'reminder_type', 'contract_status',
      'contract_type', 'deal_status', 'deal_type', 'offer_status', 'viewing_status', 'match_status',
      'opportunity_status', 'agreement_status', 'agreement_type', 'building_condition', 'orientation',
      'property_type', 'listing_type', 'property_status', 'contact_source', 'contact_type',
      'user_status', 'user_role',
    ];
    for (const e of enumTypes) await q.query(`DROP TYPE IF EXISTS ${e}`);
  }
}
