import { z } from 'zod';
import {
  listResponse,
  localizedSchema,
  paginationQuerySchema,
  currencySchema,
} from '../../schemas/common';
import {
  BUILDING_CONDITIONS,
  LISTING_TYPES,
  ORIENTATIONS,
  PROPERTY_STATUSES,
  PROPERTY_TYPES,
} from '../../schemas/enums';

export const propertyResponse = z.object({
  id: z.string().uuid(),
  propertyCode: z.string(),
  status: z.enum(PROPERTY_STATUSES),
  listingType: z.enum(LISTING_TYPES),
  propertyType: z.enum(PROPERTY_TYPES),
  titleJson: localizedSchema,
  descriptionJson: localizedSchema.nullable(),
  price: z.number(),
  currency: z.string(),
  country: z.string(),
  city: z.string(),
  area: z.string().nullable(),
  cadastralZone: z.string().nullable(),
  address: z.string().nullable(),
  latitude: z.number().nullable(),
  longitude: z.number().nullable(),
  bedrooms: z.number().nullable(),
  bathrooms: z.number().nullable(),
  toilets: z.number().nullable(),
  floor: z.number().nullable(),
  sizeM2: z.number().nullable(),
  lotSizeM2: z.number().nullable(),
  terraceM2: z.number().nullable(),
  basementM2: z.number().nullable(),
  garage: z.number().nullable(),
  parking: z.boolean(),
  elevator: z.boolean(),
  balconies: z.number().nullable(),
  storage: z.boolean(),
  furnished: z.boolean(),
  heatingTypeId: z.number().nullable(),
  orientation: z.enum(ORIENTATIONS).nullable(),
  buildingCondition: z.enum(BUILDING_CONDITIONS).nullable(),
  yearBuilt: z.number().nullable(),
  isFeatured: z.boolean(),
  attributesJson: z.record(z.unknown()),
  agentUserId: z.string().uuid(),
  ownerContactId: z.string().uuid().nullable(),
  publishedDate: z.string().nullable(),
  createdBy: z.string().uuid().nullable(),
  createdAt: z.date(),
  updatedAt: z.date(),
});

export const propertyListResponse = listResponse(propertyResponse);

const optionalInt = z.number().int().min(0).optional();
const optionalNum = z.number().min(0).optional();

export const createPropertyBody = z.object({
  status: z.enum(PROPERTY_STATUSES).default('DRAFT'),
  listingType: z.enum(LISTING_TYPES),
  propertyType: z.enum(PROPERTY_TYPES),
  titleJson: localizedSchema,
  descriptionJson: localizedSchema.optional(),
  price: z.number().min(0),
  currency: currencySchema,
  country: z.string().min(1),
  city: z.string().min(1),
  area: z.string().optional(),
  cadastralZone: z.string().optional(),
  address: z.string().optional(),
  latitude: z.number().min(-90).max(90).optional(),
  longitude: z.number().min(-180).max(180).optional(),
  bedrooms: optionalInt,
  bathrooms: optionalInt,
  toilets: optionalInt,
  floor: z.number().int().optional(),
  sizeM2: optionalNum,
  lotSizeM2: optionalNum,
  terraceM2: optionalNum,
  basementM2: optionalNum,
  garage: optionalInt,
  parking: z.boolean().default(false),
  elevator: z.boolean().default(false),
  balconies: optionalInt,
  storage: z.boolean().default(false),
  furnished: z.boolean().default(false),
  heatingTypeId: z.number().int().optional(),
  orientation: z.enum(ORIENTATIONS).optional(),
  buildingCondition: z.enum(BUILDING_CONDITIONS).optional(),
  yearBuilt: z.number().int().min(1800).optional(),
  isFeatured: z.boolean().default(false),
  attributesJson: z.record(z.unknown()).default({}),
  agentUserId: z.string().uuid(),
  ownerContactId: z.string().uuid().optional(),
  publishedDate: z.string().optional(),
});

export const updatePropertyBody = createPropertyBody.partial();

export const propertyListQuery = paginationQuerySchema.extend({
  status: z.enum(PROPERTY_STATUSES).optional(),
  listingType: z.enum(LISTING_TYPES).optional(),
  propertyType: z.enum(PROPERTY_TYPES).optional(),
  city: z.string().optional(),
  area: z.string().optional(),
  minPrice: z.coerce.number().optional(),
  maxPrice: z.coerce.number().optional(),
  bedrooms: z.coerce.number().int().optional(),
  featured: z.coerce.boolean().optional(),
  search: z.string().optional(),
});
